# This file is part of Dedipanel project
#
# (c) 2010-2015 Dedipanel <http://www.dedicated-panel.net>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

dedipanel_teamspeak_index:
    pattern: /
    defaults:
        _controller: dedipanel.controller.teamspeak:indexAction
        _sylius:
            paginate: false
            criteria:
                groups: @dedipanel.resolver.user_group:getAccessibleGroupsId
            paginate: false
            limit: false

dedipanel_teamspeak_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.teamspeak:createAction
        _sylius:
            redirect:
                route: dedipanel_teamspeak_instance_index
                parameters:
                    serverId: resource.id

dedipanel_teamspeak_update:
    pattern: /{id}/edit
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.teamspeak:updateAction
        _sylius:
            redirect: dedipanel_teamspeak_index

dedipanel_teamspeak_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: dedipanel.controller.teamspeak:deleteAction
        # template: DPTeamspeakServerBundle:TeamspeakServer:delete.html.twig

dedipanel_teamspeak_change_state:
     pattern: /{id}/change-state
     methods: [GET]
     defaults:
         _controller: dedipanel.controller.teamspeak:changeStateAction
