# This file is part of Dedipanel project
#
# (c) 2010-2015 Dedipanel <http://www.dedicated-panel.net>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

dedipanel_steam_index:
    pattern: /
    defaults:
        _controller: dedipanel.controller.steam:indexAction
        _sylius:
            paginate: false
            criteria:
                groups: @dedipanel.resolver.user_group:getAccessibleGroupsId
            paginate: false
            limit: false

dedipanel_steam_show:
    pattern: /{id}/show
    defaults:
        _controller: dedipanel.controller.steam:showAction
        _sylius:
            paginate: false

dedipanel_steam_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.steam:createAction
        _sylius:
            redirect: dedipanel_steam_index

dedipanel_steam_update:
    pattern: /{id}/edit
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.steam:updateAction

dedipanel_steam_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: dedipanel.controller.steam:deleteAction
        template: DPSteamServerBundle:SteamServer:delete.html.twig

dedipanel_steam_install:
    pattern: /{id}/install
    methods: [GET]
    defaults:
        _controller: dedipanel.controller.steam:installProgressAction

dedipanel_steam_regen:
    pattern: /{id}/regen
    methods: [GET]
    defaults:
        _controller: dedipanel.controller.steam:regenAction

dedipanel_steam_logs:
    pattern: /{id}/logs
    methods: [GET]
    defaults:
        _controller: dedipanel.controller.steam:logsAction

dedipanel_steam_change_state:
    pattern: /{id}/change-state
    methods: [GET]
    defaults:
        _controller: dedipanel.controller.steam:changeStateAction

dedipanel_steam_rcon_json:
    pattern: /{id}/rcon
    methods: [GET, POST]
    requirements:
        _format: json
    defaults:
        _format: json
        _controller: dedipanel.controller.steam:rconAction

dedipanel_steam_rcon:
    pattern: /{id}/rcon
    methods: [GET, POST]
    requirements:
        _format: html
    defaults:
        _format: html
        _controller: dedipanel.controller.steam:rconAction

dedipanel_steam_plugin_install:
    pattern: /{id}/plugin/{plugin}/install
    methods: [GET]
    defaults:
        action: install
        _controller: dedipanel.controller.steam:pluginAction

dedipanel_steam_plugin_uninstall:
    pattern: /{id}/plugin/{plugin}/uninstall
    methods: [GET]
    defaults:
        action: uninstall
        _controller: dedipanel.controller.steam:pluginAction

dedipanel_steam_plugin:
    pattern: /{id}/plugin
    methods: [GET]
    defaults:
        _controller: dedipanel.controller.steam:showAction
        _sylius:
            template: DPSteamServerBundle:SteamServer:plugin_show.html.twig

DPSteamServerBundle_FTP:
    resource: "@DPSteamServerBundle/Resources/config/routing/ftp.yml"
    prefix: /{id}/ftp/
    requirements: {id: \d+}
