# Copyright (C) 2010-2013 Kerouanton Albin, Smedts Jérôme
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

services:
    packet.factory.steam.query:
        class: DP\GameServer\SteamServerBundle\Service\PacketFactory\SteamQueryPacketFactory
    packet.factory.rcon.goldsrc:
        class: DP\GameServer\SteamServerBundle\Service\PacketFactory\GoldSrcRconPacketFactory
    packet.factory.rcon.source:
        class: DP\GameServer\SteamServerBundle\Service\PacketFactory\SourceRconPacketFactory
    
    query.steam:
        class: DP\GameServer\SteamServerBundle\Service\Query
        arguments: [ @service_container ]
    
    rcon.steam:
        class: DP\GameServer\SteamServerBundle\Service\RconService
        arguments: [ @service_container ]
    
    steam.listener.configModifier:
        class: DP\GameServer\SteamServerBundle\Listener\ConfigModifier
        arguments: [ @service_container ]
        calls:
            - [ setServiceContainer, [ @service_container ] ]
        tags:
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
    
    dedipanel.steam.form.create:
        class: DP\GameServer\SteamServerBundle\Form\SteamCreateServerType
        tags:
            - { name: form.type, alias: dedipanel_steam_create }
            
    dedipanel.steam.form.update:
        class: DP\GameServer\SteamServerBundle\Form\SteamUpdateServerType
        tags:
            - { name: form.type, alias: dedipanel_steam_update}
