# This file is part of Dedipanel project
#
# (c) 2010-2015 Dedipanel <http://www.dedicated-panel.net>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

dedipanel_machine_index:
    pattern:  /
    defaults:
        _controller: dedipanel.controller.machine:indexAction
        _sylius:
            criteria:
                groups: @dedipanel.resolver.user_group:getAccessibleGroupsId
            paginate: false
            limit: false

dedipanel_machine_show:
    pattern:  /{id}/show
    defaults:
        _controller: dedipanel.controller.machine:showAction

dedipanel_machine_create:
    pattern:  /new
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.machine:createAction

dedipanel_machine_update:
    pattern:  /{id}/edit
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.machine:updateAction

dedipanel_machine_delete:
    pattern:  /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: dedipanel.controller.machine:deleteAction
        template: DPMachineBundle:Machine:delete.html.twig

dedipanel_machine_connection_test:
    pattern:  /{id}/connectionTest
    defaults:
        _controller: dedipanel.controller.machine:testConnectionAction
