# Copyright (C) 2010-2013 Kerouanton Albin, Smedts Jérôme
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

dedipanel_machine_index:
    pattern:  /
    defaults: 
        _controller: dedipanel.controller.machine:indexAction
        _sylius:
            role: ROLE_DP_ADMIN_MACHINE_ADMIN
            paginate: false

dedipanel_machine_show:
    pattern:  /{id}/show
    defaults:
        _controller: dedipanel.controller.machine:showAction
        _sylius:
            role: ROLE_DP_ADMIN_MACHINE_ADMIN

dedipanel_machine_create:
    pattern:  /new
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.machine:createAction
        _sylius:
            form: dedipanel_machine_add
            role: ROLE_DP_ADMIN_MACHINE_ADMIN

dedipanel_machine_update:
    pattern:  /{id}/edit
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.machine:updateAction
        _sylius:
            form: dedipanel_machine_edit
            role: ROLE_DP_ADMIN_MACHINE_ADMIN

dedipanel_machine_delete:
    pattern:  /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: dedipanel.controller.machine:deleteAction
        template: DPMachineBundle:Machine:delete.html.twig
        _sylius:
            role: ROLE_DP_ADMIN_MACHINE_ADMIN

dedipanel_machine_connection_test:
    pattern:  /{id}/connectionTest
    defaults:
        _controller: dedipanel.controller.machine:testConnectionAction
        _sylius:
            role: ROLE_DP_ADMIN_MACHINE_ADMIN
