parameters:
    dp.descriptor.group_admin.routes:
        index:        group_admin
        new:          group_admin_new
        create:       group_admin_create
        edit:         group_admin_edit
        update:       group_admin_update
        delete:       group_admin_delete
        batch_delete: group_admin_batch_delete
    
    dp.descriptor.group_admin.templates:
        index:              "DPAdminUserBundle:Group:index.html.twig"
        new:                "DPAdminBundle:CRUD:new.html.twig"
        edit:               "DPAdminBundle:CRUD:edit.html.twig"
        batch_confirmation: "DPAdminBundle:CRUD:batch_confirmation.html.twig"
services:    
    dp.form.group:
        class: DP\Admin\UserBundle\Form\GroupType
    
    dp.processor.group:
        class: DP\Admin\UserBundle\Processor\GroupProcessor
        arguments: [ @fos_user.group_manager, @dp.descriptor.group_admin ]
    
    dp.descriptor.group_admin:
        class: DP\Admin\AdminBundle\Descriptor\Descriptor
        calls:
            - [ setName, [ "group_admin" ] ]
            - [ setRoutes, [ %dp.descriptor.group_admin.routes% ] ]
            - [ setTemplates, [ %dp.descriptor.group_admin.templates% ] ]
            - [ setForms, [ { add: @dp.form.group, edit: @dp.form.group } ] ]
            - [ setEntityFactory, [ @dp.entity_factory.group ] ]
            - [ setEntityRepository, [ @dp.repository.group ] ]
            - [ setProcessor, [ @dp.processor.group ] ]
            
