imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources: ['::form.html.twig']

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        []
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%
        types:
          json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb'
    firewall_name: main
    user_class: DP\Core\UserBundle\Entity\User
    profile:
        form:
            type: app_user_profile
            name: app_user_profile_form
            validation_groups: [ Profile, Default, Authentication ]
    group:
        group_class: DP\Core\UserBundle\Entity\Group
        group_manager: fos_user.group_manager.default
        form:
            type: fos_user_group
            name: fos_user_group_form
            validation_groups: [ Registration, Default ]

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:
          
knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: DPUserBundle::knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default

sylius_resource:
    resources:
        dedipanel.user:
            driver: doctrine/orm
            templates: DPUserBundle:User
            role_prefix: ROLE_DP_ADMIN_USER
            classes:
                model: DPUserBundle:User
                repository: DP\Core\UserBundle\Entity\UserRepository
        dedipanel.group:
            driver: doctrine/orm
            templates: DPUserBundle:Group
            role_prefix: ROLE_DP_ADMIN_GROUP
            classes:
                model: DPUserBundle:Group
                repository: DP\Core\UserBundle\Entity\GroupRepository
        dedipanel.machine:
            driver: doctrine/orm
            templates: DPMachineBundle:Machine
            role_prefix: ROLE_DP_ADMIN_MACHINE
            classes:
                model: DPMachineBundle:Machine
                controller: DP\Core\MachineBundle\Controller\MachineController
        dedipanel.game:
            driver: doctrine/orm
            templates: DPGameBundle:Game
            role_prefix: ROLE_DP_ADMIN_GAME
            classes:
                model: DPGameBundle:Game
        dedipanel.plugin:
            driver: doctrine/orm
            templates: DPGameBundle:Plugin
            role_prefix: ROLE_DP_ADMIN_PLUGIN
            classes:
                model: DPGameBundle:Plugin
        dedipanel.steam:
            driver: doctrine/orm
            templates: DPSteamServerBundle:SteamServer
            role_prefix: ROLE_DP_GAME_STEAM
            classes:
                model: DPSteamServerBundle:SteamServer
                controller: DP\GameServer\GameServerBundle\Controller\GameServerController
        dedipanel.steam.ftp:
            driver: doctrine/orm
            templates: DPSteamServerBundle:FTP
            classes:
                model: DPSteamServerBundle:SteamServer
                controller: DP\GameServer\GameServerBundle\Controller\FTPController
