security:
    role_hierarchy:
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_DP_ADMIN_GAME_ADMIN
            - ROLE_DP_ADMIN_PLUGIN_ADMIN
            - ROLE_DP_GAME_STEAM_ADMIN
            - ROLE_DP_GAME_MINECRAFT_ADMIN
            - ROLE_DP_VOIP_TEAMSPEAK_ADMIN
            - ROLE_DP_VOIP_TEAMSPEAK_INSTANCE_ADMIN
#            - ROLE_ALLOWED_TO_SWITCH
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_DP_ADMIN_USER_ADMIN
            - ROLE_DP_ADMIN_GROUP_ADMIN
            - ROLE_DP_ADMIN_MACHINE_ADMIN
        ROLE_DP_ADMIN_USER_ADMIN: 
            - ROLE_DP_ADMIN_USER_INDEX
            - ROLE_DP_ADMIN_USER_SHOW
            - ROLE_DP_ADMIN_USER_CREATE
            - ROLE_DP_ADMIN_USER_UPDATE
            - ROLE_DP_ADMIN_USER_DELETE
            - ROLE_USER
        ROLE_DP_ADMIN_GROUP_ADMIN: 
            - ROLE_DP_ADMIN_GROUP_INDEX
            - ROLE_DP_ADMIN_GROUP_SHOW
            - ROLE_DP_ADMIN_GROUP_CREATE
            - ROLE_DP_ADMIN_GROUP_UPDATE
            - ROLE_DP_ADMIN_GROUP_DELETE
            - ROLE_USER
        ROLE_DP_ADMIN_MACHINE_ADMIN: 
            - ROLE_DP_ADMIN_MACHINE_INDEX
            - ROLE_DP_ADMIN_MACHINE_SHOW
            - ROLE_DP_ADMIN_MACHINE_CREATE
            - ROLE_DP_ADMIN_MACHINE_UPDATE
            - ROLE_DP_ADMIN_MACHINE_DELETE
            - ROLE_USER
        ROLE_DP_ADMIN_GAME_ADMIN: 
            - ROLE_DP_ADMIN_GAME_INDEX
            - ROLE_DP_ADMIN_GAME_SHOW
            - ROLE_DP_ADMIN_GAME_CREATE
            - ROLE_DP_ADMIN_GAME_UPDATE
            - ROLE_DP_ADMIN_GAME_DELETE
            - ROLE_USER
        ROLE_DP_ADMIN_PLUGIN_ADMIN: 
            - ROLE_DP_ADMIN_PLUGIN_INDEX
            - ROLE_DP_ADMIN_PLUGIN_SHOW
            - ROLE_DP_ADMIN_PLUGIN_CREATE
            - ROLE_DP_ADMIN_PLUGIN_UPDATE
            - ROLE_DP_ADMIN_PLUGIN_DELETE
            - ROLE_USER
        ROLE_DP_GAME_STEAM_ADMIN:
            - ROLE_DP_GAME_STEAM_INDEX
            - ROLE_DP_GAME_STEAM_SHOW
            - ROLE_DP_GAME_STEAM_CREATE
            - ROLE_DP_GAME_STEAM_UPDATE
            - ROLE_DP_GAME_STEAM_DELETE
            - ROLE_DP_GAME_STEAM_STATE
            - ROLE_DP_GAME_STEAM_RCON
            - ROLE_DP_GAME_STEAM_PLUGIN
            - ROLE_DP_GAME_STEAM_FTP
            - ROLE_USER
        ROLE_DP_GAME_MINECRAFT_ADMIN:
            - ROLE_DP_GAME_MINECRAFT_INDEX
            - ROLE_DP_GAME_MINECRAFT_SHOW
            - ROLE_DP_GAME_MINECRAFT_CREATE
            - ROLE_DP_GAME_MINECRAFT_UPDATE
            - ROLE_DP_GAME_MINECRAFT_DELETE
            - ROLE_DP_GAME_MINECRAFT_STATE
            - ROLE_DP_GAME_MINECRAFT_RCON
            - ROLE_DP_GAME_MINECRAFT_PLUGIN
            - ROLE_DP_GAME_MINECRAFT_FTP
            - ROLE_USER
        ROLE_DP_VOIP_TEAMSPEAK_ADMIN:
            - ROLE_DP_VOIP_TEAMSPEAK_INSTANCE_ADMIN
            - ROLE_DP_VOIP_TEAMSPEAK_INDEX
            - ROLE_DP_VOIP_TEAMSPEAK_SHOW
            - ROLE_DP_VOIP_TEAMSPEAK_CREATE
            - ROLE_DP_VOIP_TEAMSPEAK_UPDATE
            - ROLE_DP_VOIP_TEAMSPEAK_DELETE
            - ROLE_DP_VOIP_TEAMSPEAK_STATE
            - ROLE_USER
        ROLE_DP_VOIP_TEAMSPEAK_INSTANCE_ADMIN:
            - ROLE_DP_VOIP_TEAMSPEAK_INSTANCE_INDEX
            - ROLE_DP_VOIP_TEAMSPEAK_INSTANCE_SHOW
            - ROLE_DP_VOIP_TEAMSPEAK_INSTANCE_CREATE
            - ROLE_DP_VOIP_TEAMSPEAK_INSTANCE_UPDATE
            - ROLE_DP_VOIP_TEAMSPEAK_INSTANCE_DELETE
            - ROLE_DP_VOIP_TEAMSPEAK_INSTANCE_STATE
            - ROLE_USER
