security:   
    role_hierarchy:
        ROLE_SUPER_ADMIN: 
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
        ROLE_ADMIN: 
            - ROLE_USER
            - ROLE_DP_ADMIN_USER_ADMIN
            - ROLE_DP_ADMIN_GROUP_ADMIN
            - ROLE_DP_ADMIN_MACHINE_ADMIN
            - ROLE_DP_ADMIN_GAME_ADMIN
            - ROLE_DP_ADMIN_PLUGIN_ADMIN
        ROLE_DP_ADMIN_USER_ADMIN: 
            - ROLE_DP_ADMIN_USER_INDEX
            - ROLE_DP_ADMIN_USER_SHOW
            - ROLE_DP_ADMIN_USER_CREATE
            - ROLE_DP_ADMIN_USER_UPDATE
            - ROLE_DP_ADMIN_USER_DELETE
            - ROLE_USER
        ROLE_DP_ADMIN_GROUP_ADMIN: 
            - ROLE_DP_ADMIN_GROUP_INDEX
            - ROLE_DP_ADMIN_GROUP_SHOW
            - ROLE_DP_ADMIN_GROUP_CREATE
            - ROLE_DP_ADMIN_GROUP_UPDATE
            - ROLE_DP_ADMIN_GROUP_DELETE
            - ROLE_USER
        ROLE_DP_ADMIN_MACHINE_ADMIN: 
            - ROLE_DP_ADMIN_MACHINE_INDEX
            - ROLE_DP_ADMIN_MACHINE_SHOW
            - ROLE_DP_ADMIN_MACHINE_CREATE
            - ROLE_DP_ADMIN_MACHINE_UPDATE
            - ROLE_DP_ADMIN_MACHINE_DELETE
            - ROLE_USER
        ROLE_DP_ADMIN_GAME_ADMIN: 
            - ROLE_DP_ADMIN_GAME_INDEX
            - ROLE_DP_ADMIN_GAME_SHOW
            - ROLE_DP_ADMIN_GAME_CREATE
            - ROLE_DP_ADMIN_GAME_UPDATE
            - ROLE_DP_ADMIN_GAME_DELETE
            - ROLE_USER
        ROLE_DP_ADMIN_PLUGIN_ADMIN: 
            - ROLE_DP_ADMIN_PLUGIN_INDEX
            - ROLE_DP_ADMIN_PLUGIN_SHOW
            - ROLE_DP_ADMIN_PLUGIN_CREATE
            - ROLE_DP_ADMIN_PLUGIN_UPDATE
            - ROLE_DP_ADMIN_PLUGIN_DELETE
            - ROLE_USER
