security:   
    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN:       [ROLE_USER, ROLE_DP_ADMIN, ROLE_DP_ADMIN_USER_ADMIN, ROLE_DP_ADMIN_GROUP_ADMIN, ROLE_DP_ADMIN_MACHINE_ADMIN, ROLE_DP_ADMIN_GAME_ADMIN, ROLE_DP_ADMIN_PLUGIN_ADMIN]
        ROLE_DP_ADMIN_USER_ADMIN: [ROLE_DP_ADMIN_USER_ADMIN]
        ROLE_DP_ADMIN_GROUP_ADMIN: [ROLE_DP_ADMIN_GROUP_ADMIN]
        ROLE_DP_ADMIN_MACHINE_ADMIN: [ROLE_DP_ADMIN_MACHINE_ADMIN]
        ROLE_DP_ADMIN_GAME_ADMIN: [ROLE_DP_ADMIN_GAME_ADMIN]
        ROLE_DP_ADMIN_PLUGIN_ADMIN: [ROLE_DP_ADMIN_PLUGIN_ADMIN]
