_welcome:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: dedipanel_installer
        permanent: true

installer:
    resource: "@DPDistributionBundle/Resources/config/routing.yml"
    prefix:   /installer/

# Needed for the final redirection
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
