# (c) 2010-2014 Dedipanel <http://www.dedicated-panel.net>
# 
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

_main:
    resource: routing.yml

installer:
    resource: "@DPDistributionBundle/Resources/config/routing.yml"
    prefix:   /installer/

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler
