# This file is part of Dedipanel project
#
# (c) 2010-2014 Dedipanel <http://www.dedicated-panel.net>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

dedipanel_game_index:
    pattern: /
    defaults:
        _controller: dedipanel.controller.game:indexAction
        _sylius:
            paginate: false
            limit: false

dedipanel_game_show:
    pattern: /{id}/show
    defaults:
        _controller: dedipanel.controller.game:showAction

dedipanel_game_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.game:createAction

dedipanel_game_update:
    pattern: /{id}/edit
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.game:updateAction

dedipanel_game_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: dedipanel.controller.game:deleteAction
        template: DPGameBundle:Game:delete.html.twig
