services:    
    dedipanel.security.form.roles_type:
        class: DP\Core\UserBundle\Form\Type\RolesType
        arguments: [ @dedipanel.security.form.roles_type.subscriber, %security.role_hierarchy.roles%, @translator ]
        tags:
            - { name: form.type, alias: dp_security_roles }
    
    dedipanel.security.form.roles_type.subscriber:
        class: DP\Core\UserBundle\EventListener\RolesTypeSubscriber
        arguments: [ @security.role_hierarchy, %security.role_hierarchy.roles% ]
