game_admin:
    pattern:  /
    defaults: { _controller: "DPAdminGameBundle:Game:index" }

game_admin_show:
    pattern:  /{id}/show
    defaults: { _controller: "DPAdminGameBundle:Game:show" }

game_admin_new:
    pattern:  /new
    defaults: { _controller: "DPAdminGameBundle:Game:new" }

game_admin_create:
    pattern:  /create
    defaults: { _controller: "DPAdminGameBundle:Game:create" }
    requirements: { _method: post }

game_admin_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "DPAdminGameBundle:Game:edit" }

game_admin_update:
    pattern:  /{id}/update
    defaults: { _controller: "DPAdminGameBundle:Game:update" }
    requirements: { _method: post|put }

game_admin_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "DPAdminGameBundle:Game:delete" }
    requirements: { _method: post|delete }
    
game_admin_batch_delete:
    pattern:  /batch/delete
    defaults: { _controller: "DPAdminGameBundle:Game:batchDelete" }
    requirements: { _method: post|delete }
