# Copyright (C) 2010-2013 Kerouanton Albin, Smedts Jérôme
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

dedipanel_minecraft_index:
    pattern: /
    defaults:
        _controller: dedipanel.controller.minecraft:indexAction
        _sylius:
            paginate: false
            criteria:
                groups: @dedipanel.resolver.user_group:getAccessibleGroupsIdOrEmpty

dedipanel_minecraft_show:
    pattern: /{id}/show
    defaults:
        _controller: dedipanel.controller.minecraft:showAction
        _sylius:
            paginate: false

dedipanel_minecraft_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.minecraft:createAction
        _sylius:
            redirect: dedipanel_minecraft_index

dedipanel_minecraft_update:
    pattern: /{id}/edit
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.minecraft:updateAction

dedipanel_minecraft_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: dedipanel.controller.minecraft:deleteAction

dedipanel_minecraft_install:
    pattern: /{id}/install
    methods: [GET]
    defaults:
        _controller: dedipanel.controller.minecraft:installProgressAction

dedipanel_minecraft_regen:
    pattern: /{id}/regen
    methods: [GET]
    defaults:
        _controller: dedipanel.controller.minecraft.regenAction

dedipanel_minecraft_logs:
    pattern: /{id}/logs
    methods: [GET]
    defaults:
        _controller: dedipanel.controller.minecraft:logsAction

dedipanel_minecraft_change_state:
    pattern: /{id}/change-state
    methods: [GET]
    defaults:
        _controller: dedipanel.controller.minecraft:changeStateAction

dedipanel_minecraft_rcon:
    pattern: /{id}/rcon
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.minecraft:rconAction

dedipanel_minecraft_plugin:
    pattern: /{id}/plugin
    methods: [GET]
    defaults:
        _controller: dedipanel.controller.minecraft:showAction
        _sylius:
            template: DPGameServerBundle:Plugin:show.html.twig

dedipanel_minecraft_plugin_install:
    pattern: /{id}/plugin/{plugin}/install
    methods: [GET]
    defaults:
        _controller: dedipanel.controller.minecraft:pluginAction

dedipanel_minecraft_plugin_uninstall:
    pattern: /{id}/plugin/{plugin}/uninstall
    methods: [GET]
    defaults:
        _controller: dedipanel.controller.minecraft:pluginAction
  
DPMinecraftServerBundle_FTP:
    resource: "@DPMinecraftServerBundle/Resources/config/routing/ftp.yml"
    prefix: /{id}/ftp/
    requirements: {id: \d+}
