# (c) 2010-2014 Dedipanel <http://www.dedicated-panel.net>
# 
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

dedipanel_minecraft_index:
    pattern: /
    defaults:
        _controller: dedipanel.controller.minecraft:indexAction
        _sylius:
            paginate: false
            criteria:
                groups: @dedipanel.resolver.user_group:getAccessibleGroupsIdOrEmpty

dedipanel_minecraft_show:
    pattern: /{id}/show
    defaults:
        _controller: dedipanel.controller.minecraft:showAction
        _sylius:
            paginate: false

dedipanel_minecraft_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.minecraft:createAction
        _sylius:
            redirect: dedipanel_minecraft_index

dedipanel_minecraft_update:
    pattern: /{id}/edit
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.minecraft:updateAction

dedipanel_minecraft_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: dedipanel.controller.minecraft:deleteAction

dedipanel_minecraft_install:
    pattern: /{id}/install
    methods: [GET]
    defaults:
        _controller: dedipanel.controller.minecraft:installProgressAction

dedipanel_minecraft_regen:
    pattern: /{id}/regen
    methods: [GET]
    defaults:
        _controller: dedipanel.controller.minecraft.regenAction

dedipanel_minecraft_logs:
    pattern: /{id}/logs
    methods: [GET]
    defaults:
        _controller: dedipanel.controller.minecraft:logsAction

dedipanel_minecraft_change_state:
    pattern: /{id}/change-state
    methods: [GET]
    defaults:
        _controller: dedipanel.controller.minecraft:changeStateAction

dedipanel_minecraft_rcon:
    pattern: /{id}/rcon
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.minecraft:rconAction

dedipanel_minecraft_plugin:
    pattern: /{id}/plugin
    methods: [GET]
    defaults:
        _controller: dedipanel.controller.minecraft:showAction
        _sylius:
            template: DPGameServerBundle:Plugin:show.html.twig

dedipanel_minecraft_plugin_install:
    pattern: /{id}/plugin/{plugin}/install
    methods: [GET]
    defaults:
        _controller: dedipanel.controller.minecraft:pluginAction

dedipanel_minecraft_plugin_uninstall:
    pattern: /{id}/plugin/{plugin}/uninstall
    methods: [GET]
    defaults:
        _controller: dedipanel.controller.minecraft:pluginAction
  
DPMinecraftServerBundle_FTP:
    resource: "@DPMinecraftServerBundle/Resources/config/routing/ftp.yml"
    prefix: /{id}/ftp/
    requirements: {id: \d+}
