# This file is part of Dedipanel project
#
# (c) 2010-2014 Dedipanel <http://www.dedicated-panel.net>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

game_admin:
    resource: "@DPGameBundle/Resources/config/routing/game.yml"
    prefix:   /game
    
plugin_admin:
    resource: "@DPGameBundle/Resources/config/routing/plugin.yml"
    prefix:   /plugin
