services:
    monolog.processor.psr_log_message:
        class: Monolog\Processor\PsrLogMessageProcessor
        tags:
          - { name: monolog.processor }

    dp_menu.factory:
        class: DP\Core\CoreBundle\Menu\MenuFactory
        arguments: [ "@router" ]

    dp_menu.menu_builder:
        class: DP\Core\CoreBundle\Menu\MenuBuilder
        arguments: [ @dp_menu.factory, @security.context ]

    dp_menu.main_menu:
        class: DP\Core\Menu\MenuItem
        factory_service: dp_menu.menu_builder
        factory_method: createMainMenu
        arguments: [ "@request" ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }

    dp_core.update_watcher.service:
        class: DP\Core\CoreBundle\Service\UpdateWatcherService
        arguments: [ "%dedipanel.version%", "%kernel.cache_dir%" ]

    dp_core.twig_extension:
        class: DP\Core\CoreBundle\Twig\CoreExtension
        arguments: [ @dp_core.update_watcher.service, "%dedipanel.debug%" ]
        tags:
            - { name: twig.extension }

    dedipanel.core.form_error.extension:
        class: DP\Core\CoreBundle\Form\FormErrorExtension
        tags:
            - { name: form.type_extension, alias: form }

    dedipanel.kernel.controller.service_args:
        class: DP\Core\CoreBundle\EventListener\RoutingServiceArgsListener
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
