services:
    monolog.processor.psr_log_message:
        class: Monolog\Processor\PsrLogMessageProcessor
        tags:
          - { name: monolog.processor }

    dp_core.update_watcher.service:
        class: DP\Core\CoreBundle\Service\UpdateWatcherService
        arguments: [ "%dp_core.version%" ]

    dp_core.update_watcher.extension:
        class: DP\Core\CoreBundle\Extension\UpdateWatcherExtension
        arguments: [ @dp_core.update_watcher.service ]
        tags:
            - { name: twig.extension }

    dp_menu.factory:
        class: DP\Core\CoreBundle\Menu\MenuFactory
        arguments: [ "@router" ]

    dp_menu.menu_builder:
        class: DP\Core\CoreBundle\Menu\MenuBuilder
        arguments: [ @dp_menu.factory, @security.context ]

    dp_menu.main_menu:
        class: DP\Core\Menu\MenuItem
        factory_service: dp_menu.menu_builder
        factory_method: createMainMenu
        arguments: [ "@request" ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }

    dedipanel.core.form_error.extension:
        class: DP\Core\CoreBundle\Extension\FormErrorExtension
        tags:
            - { name: form.type_extension, alias: form }
