# This file is part of Dedipanel project
#
# (c) 2010-2015 Dedipanel <http://www.dedicated-panel.net>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# This specific route is catched by the UserAdminListener
# and the groups criteria is deleted for super admin
# ensuring they can access to others super admin
dedipanel_user_index:
    pattern: /
    defaults:
        _controller: dedipanel.controller.user:indexAction
        _sylius:
            criteria:
                groups: @dedipanel.resolver.user_group:getAccessibleGroupsId
            paginate: false
            limit: false

dedipanel_user_show:
    pattern: /{id}/show
    defaults:
        _controller: dedipanel.controller.user:showAction

dedipanel_user_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.user:createAction

dedipanel_user_update:
    pattern: /{id}/edit
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.user:updateAction

dedipanel_user_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: dedipanel.controller.user:deleteAction
        template: DPUserBundle:User:delete.html.twig
