user_admin:
    pattern:  /
    defaults: { _controller: "DPAdminUserBundle:User:index" }

user_admin_new:
    pattern:  /new
    defaults: { _controller: "DPAdminUserBundle:User:new" }

user_admin_create:
    pattern:  /create
    defaults: { _controller: "DPAdminUserBundle:User:create" }
    requirements: { _method: post }

user_admin_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "DPAdminUserBundle:User:edit" }

user_admin_update:
    pattern:  /{id}/update
    defaults: { _controller: "DPAdminUserBundle:User:update" }
    requirements: { _method: post|put }
    
user_admin_batch_delete:
    pattern:  /batch/delete
    defaults: { _controller: "DPAdminUserBundle:User:batchDelete" }
    requirements: { _method: post|delete }

user_admin_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "DPAdminUserBundle:User:delete" }
    requirements: { _method: post|delete }

user_admin_change_status:
    pattern: /{id}/{newStatus}
    defaults: { _controller: "DPAdminUserBundle:User:changeStatus" }
    requirements: { newStatus: "enabled|disabled" }

user_admin_edit_roles:
    pattern:  /{id}/edit-roles
    defaults: { _controller: "DPAdminUserBundle:User:editRoles" }

user_admin_update_roles:
    pattern:  /{id}/edit-roles
    defaults: { _controller: "DPAdminUserBundle:User:updateRoles" }
    requirements: {Â _method: post|put }
