# Copyright (C) 2010-2013 Kerouanton Albin, Smedts Jérôme
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

parameters:
    socket.timeout: [1, 0]
    
services:
    socket:
        class: DP\GameServer\GameServerBundle\Service\SocketFactory
        arguments: [ %socket.timeout% ]
    
    packet.factory:
        class: DP\GameServer\GameServerBundle\Service\PacketFactory
    
    game.listener.queryInjector:
        class: DP\GameServer\GameServerBundle\Listener\QueryInjector
        tags: 
            - { name: doctrine.event_listener, event: postLoad, method: postLoad }
    
    dedipanel.game.ftp.form.file:
        class: DP\GameServer\GameServerBundle\Form\FTPFileType
        tags:
            - { name: form.type, alias: dedipanel_game_ftp_file }
    
    dedipanel.game.ftp.form.directory:
        class: DP\GameServer\GameServerBundle\Form\FTPDirectoryType
        tags:
            - { name: form.type, alias: dedipanel_game_ftp_directory }
