parameters:
    socket.timeout: [0, 500]
    
services:
    socket:
        class: DP\GameServer\GameServerBundle\Service\SocketFactory
        arguments: [ %socket.timeout% ]
    
    packet.factory:
        class: DP\GameServer\GameServerBundle\Service\PacketFactory