# Copyright (C) 2010-2013 Kerouanton Albin, Smedts Jérôme
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

parameters:
    socket.timeout: [1, 0]
    
services:
    socket:
        class: DP\GameServer\GameServerBundle\Service\SocketFactory
        arguments: [ %socket.timeout% ]
    
    packet.factory:
        class: DP\GameServer\GameServerBundle\Service\PacketFactory
    
    game.listener.queryInjector:
        class: DP\GameServer\GameServerBundle\Listener\QueryInjector
        arguments: [ @service_container ]
        calls:
            - [ setServiceContainer, [ @service_container ] ]
        tags: 
            - { name: doctrine.event_listener, event: postLoad, method: postLoad }
    
    game.listener.configModifier:
        class: DP\GameServer\GameServerBundle\Listener\ConfigModifier
        arguments: [ @service_container ]
        calls:
            - [ setServiceContainer, [ @service_container ] ]
        tags:
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
    
    dp.game.role_builder:
        class: DP\GameServer\GameServerBundle\Security\GameRoleBuilder
        tags:
            - { name: dp.role_builder, children_builder_tag: dp.game_role_builder }
