# This file is part of Dedipanel project
#
# (c) 2010-2015 Dedipanel <http://www.dedicated-panel.net>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    dedipanel.teamspeak.form:
        class: DP\VoipServer\TeamspeakServerBundle\Form\TeamspeakServerType
        tags:
            - { name: form.type, alias: dedipanel_teamspeak }

    dedipanel.teamspeak.instance.form:
        class: DP\VoipServer\TeamspeakServerBundle\Form\TeamspeakServerInstanceType
        tags:
            - { name: form.type, alias: dedipanel_teamspeak_instance }

    dedipanel.factory.teamspeak.query:
        class: DP\VoipServer\TeamspeakServerBundle\Service\ServerQueryFactory

    dedipanel.teamspeak.listener.configUpdate:
        class: DP\VoipServer\TeamspeakServerBundle\EventListener\ConfigUpdateListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
            - { name: kernel.event_listener, event: dedipanel.teamspeak.instance.pre_update, method: preUpdateTeamspeakInstance }

    dedipanel.teamspeak.instance_viewer:
        class: DP\VoipServer\TeamspeakServerBundle\Service\TeamspeakInstanceViewer
        arguments: [ @service_container ]
        tags:
            - { name: twig.extension }
