# Copyright (C) 2010-2012 Kerouanton Albin, Smedts Jérôme
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

user_menu:
    pattern: /
    defaults: { _controller: ApplicationSonataUserBundle:User:homeMenu }

game_menu:
    pattern: /menu/game
    defaults: { _controller: ApplicationSonataUserBundle:User:gameMenu }

config_menu:
    pattern: /menu/config
    defaults: { _controller: ApplicationSonataUserBundle:User:configMenu }


# contient la route pour le /login, important
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

    # les routes pour l'inscription (inscription, confirmation email, etc.)
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
    
# les routes pour redéfinir son mot de passe (envoi du mail, etc.)
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
    
# les routes pour les profils utilisateurs (voir et éditer un profil)
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

# une route pour changer de mot de passe
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

_sonata_admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    type: sonata_admin
    prefix: /admin

sonata_user_impersonating:
    pattern: /