services:
    app_user.auth.form.type:
        class: Application\Sonata\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: app_user_auth }
