# (c) 2010-2014 Dedipanel <http://www.dedicated-panel.net>
# 
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# Admin
user_admin:
    resource: "@DPUserBundle/Resources/config/routing/user_admin.yml"
    prefix: /user

group_admin:
    resource: "@DPUserBundle/Resources/config/routing/group_admin.yml"
    prefix: /group
